import Link from "next/link";
import { ArrowUpRight, Check, CircleHelp } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

const included = ["A focused one-page or small multi-page website", "Responsive design for phones, tablets, and desktops", "Clear calls to action and contact path", "Basic SEO metadata and performance setup", "One structured review round", "A practical handoff after launch"];

export default function PricingPage() {
  return (
    <div>
      <SiteHeader />
      <main>
        <section className="border-b border-[var(--line)] bg-[var(--surface-muted)]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><p className="eyebrow">Pricing</p><div className="mt-6 grid gap-12 lg:grid-cols-[1fr_0.8fr] lg:items-end"><h1 className="text-balance max-w-4xl text-[clamp(3.5rem,8vw,8.5rem)] font-semibold leading-[0.87] tracking-[-0.08em]">Keep the price simple. Keep the work sharp.</h1><p className="max-w-md text-lg leading-8 text-[var(--ink-muted)]">A small-business website should be easy to understand before you buy it. Here is the baseline.</p></div></div></section>
        <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div className="rounded-[2rem] bg-[var(--night)] p-7 text-[var(--background)] sm:p-10"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow text-[var(--background)]/55">Launch website</p><p className="mt-5 text-[clamp(4rem,8vw,7rem)] font-semibold leading-none tracking-[-0.08em]">$90</p><p className="mt-3 text-sm text-[var(--background)]/60">one-time setup</p></div><span className="rounded-full bg-[var(--accent)] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#151515]">Core offer</span></div><div className="my-9 h-px bg-[var(--background)]/15" /><div className="grid gap-4 sm:grid-cols-2">{included.map((item) => <p key={item} className="flex items-start gap-3 text-sm leading-6 text-[var(--background)]/75"><Check size={16} className="mt-0.5 shrink-0 text-[var(--accent)]" />{item}</p>)}</div><Link href="/book" className="mt-10 inline-flex items-center gap-2 rounded-full bg-[var(--accent)] px-5 py-3.5 text-sm font-semibold text-[#151515] hover:-translate-y-0.5">Book a free consultation <ArrowUpRight size={16} /></Link></div><div className="rounded-[2rem] border border-[var(--line)] bg-[var(--surface)] p-7 sm:p-10"><p className="eyebrow">Optional care</p><p className="mt-5 text-[clamp(4rem,8vw,7rem)] font-semibold leading-none tracking-[-0.08em]">$9<span className="text-2xl tracking-[-0.04em]">/mo</span></p><p className="mt-3 max-w-xs text-sm leading-6 text-[var(--ink-muted)]">For the small updates and gentle maintenance that keep a launch-ready site useful.</p><div className="my-9 h-px bg-[var(--line)]" /><div className="space-y-4 text-sm text-[var(--ink-muted)]"><p className="flex gap-3"><Check size={16} className="mt-0.5 shrink-0 text-[var(--accent-strong)]" />Basic maintenance status</p><p className="flex gap-3"><Check size={16} className="mt-0.5 shrink-0 text-[var(--accent-strong)]" />Small content updates</p><p className="flex gap-3"><Check size={16} className="mt-0.5 shrink-0 text-[var(--accent-strong)]" />A clear request path</p></div><p className="mt-9 flex gap-2 text-xs leading-5 text-[var(--ink-muted)]"><CircleHelp size={14} className="mt-0.5 shrink-0" />Maintenance scope, taxes, domains, and third-party tools are confirmed in your terms before work begins.</p></div></div></section>
        <section className="border-y border-[var(--line)]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[0.7fr_1.3fr] lg:px-8"><h2 className="text-3xl font-semibold tracking-[-0.05em]">No hidden “enterprise” step.</h2><div className="grid gap-5 text-sm leading-6 text-[var(--ink-muted)] sm:grid-cols-2"><p>Third-party subscriptions, domain registration, paid media, premium assets, and taxes are not quietly bundled into the headline price.</p><p>The 24-hour target is conditional on receiving the agreed content, access, and feedback. It is a delivery target, not a promise to rush unsuitable work.</p></div></div></section>
      </main>
      <SiteFooter />
    </div>
  );
}
